from typing import Optional, Dict
from backend.app.services.github_service import (
    get_pr_diff, post_pr_comment, get_repo_info, list_open_prs
)
from backend.app.agents.base_agent import BaseAgent
from backend.app.core.audit import log_audit_event
from backend.app.core.observability import get_langfuse_client


class GitHubAgent:
    """
    GitHub Integration Agent — reads PRs, posts reviews, generates docs.
    Ties into the existing reviewer agent for the actual LLM review.
    This is what 'AI coding agent' means on your CV.
    """

    def __init__(self):
        self.reviewer = BaseAgent(agent_type="reviewer")
        self.documenter = BaseAgent(agent_type="documenter")
        self.langfuse = get_langfuse_client()

    async def review_pr(
        self,
        repo_name: str,
        pr_number: int,
        user: str = "github-agent",
        post_comment: bool = True,
    ) -> Dict:
        """
        Full PR review pipeline:
        1. Fetch PR diff from GitHub
        2. Run reviewer agent against the diff
        3. Post review as GitHub PR comment
        4. Return review result
        """
        trace = self.langfuse.trace(
            name="github.pr_review",
            user_id=user,
            tags=["github", "pr_review"],
            metadata={"repo": repo_name, "pr": pr_number},
        )

        # fetch PR data
        fetch_span = trace.span(name="github.fetch_pr")
        try:
            pr_data = get_pr_diff(repo_name, pr_number)
        except Exception as e:
            fetch_span.end(output={"error": str(e)})
            return {"status": "error", "detail": f"Failed to fetch PR: {e}"}
        fetch_span.end(output={"files": len(pr_data["files_changed"])})

        # build review task from diff
        diff_summary = "\n".join([
            f"File: {f['filename']} (+{f['additions']} -{f['deletions']})\n{f['patch']}"
            for f in pr_data["files_changed"][:5]  # limit to 5 files
        ])

        review_task = f"""Review this GitHub Pull Request:

Title: {pr_data['title']}
Author: {pr_data['author']}
Branch: {pr_data['head_branch']} → {pr_data['base_branch']}
Changes: +{pr_data['additions']} -{pr_data['deletions']} lines

Files Changed:
{diff_summary}

Provide a thorough code review focusing on:
1. Security vulnerabilities
2. Logic errors and bugs
3. Code quality and best practices
4. Performance concerns
5. Overall recommendation (approve/request changes)"""

        # run reviewer agent
        review_span = trace.span(name="agent.reviewer")
        result = await self.reviewer.run(
            task=review_task,
            user=user,
        )
        review_output = result["output"]
        review_span.end(output={"review_length": len(review_output)})

        # format and post comment
        comment = f"""## 🤖 MoreAI Automated PR Review

**Repository:** `{repo_name}` | **PR:** #{pr_number}

{review_output}

---
*Generated by MoreAI Multi-Agent SDLC Platform*
"""

        comment_posted = False
        if post_comment:
            comment_span = trace.span(name="github.post_comment")
            comment_posted = post_pr_comment(repo_name, pr_number, comment)
            comment_span.end(output={"posted": comment_posted})

        log_audit_event(
            action="github:pr_review",
            user=user,
            resource=f"{repo_name}/pull/{pr_number}",
            detail=f"comment_posted={comment_posted}",
        )

        trace.update(output={"review_length": len(review_output), "comment_posted": comment_posted})

        return {
            "status": "success",
            "repo": repo_name,
            "pr_number": pr_number,
            "review": review_output,
            "comment_posted": comment_posted,
            "pr_title": pr_data["title"],
            "files_reviewed": len(pr_data["files_changed"]),
        }

    async def generate_pr_docs(
        self,
        repo_name: str,
        pr_number: int,
        user: str = "github-agent",
    ) -> Dict:
        """Generates documentation for code changes in a PR."""
        pr_data = get_pr_diff(repo_name, pr_number)
        code_changes = "\n".join([
            f"# {f['filename']}\n{f['patch']}"
            for f in pr_data["files_changed"][:3]
        ])

        result = await self.documenter.run(
            task=f"Generate documentation for these code changes:\n{code_changes}",
            user=user,
        )
        return {
            "status": "success",
            "pr_number": pr_number,
            "documentation": result["output"],
        }
        