apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: moreai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2          # AWS EBS storage class
  resources:
    requests:
      storage: 10Gi